### PR TITLE
Feature/restaurant

### PR DESCRIPTION
**Pull request by Nasa28**
In this project, I built a single-page restaurant website using Javascript.  All the content of the page was added using only Javascript. The project is built using:
1. Webpack
2. CSS

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Nasa28, congratulations on this project :smile: The rule for thenode_modules directory on .gitignore added :+1: The page is loaded using the document.create and document.appendChild :100: There is a tabbed menu :slightly_smiling_face: The content of each tab is stored in a module :smile: Each module exports a function which creates a div

There are a few missing requirement that needs to be addressed:
- Do not make any changes to the linters files, because they represent a standard for the students of Microvserse. You can find the file [here](https://www.linkedin.com/in/daniel-larbi-addo/)
- We can also improve our script so we can run commands like "npm run dev" for development and "npm run build" for production as in the example below:
`
 "dev": "webpack --mode development",
    "build": "webpack --mode production",
`

Once these are addressed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure all previously requested changes and push the commit before requesting a new review.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello @Nasa28  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [ ] As requested in the previous review, kindly ensure you use the same eslint config rules as stated in this [link](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json). They help to improve the professionalism of the codebase and if you feel changes should be made to them kindly raise a PR.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Pull request merged**
